# Generated by Django 5.2.4 on 2025-07-23 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='cross_count_name_3a2814_idx')],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rtsp_link', models.URLField(max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cross_counting.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrossCountingData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=200)),
                ('device_ip', models.GenericIPAddressField()),
                ('device_mac', models.CharField(max_length=17)),
                ('time', models.DateTimeField()),
                ('channel', models.CharField(max_length=200)),
                ('channel_alias', models.CharField(blank=True, max_length=200)),
                ('cc_in_count', models.PositiveIntegerField(default=0)),
                ('cc_out_count', models.PositiveIntegerField(default=0)),
                ('cc_total_count', models.PositiveIntegerField(default=0)),
                ('alarm_snapshot', models.BooleanField(default=False)),
                ('alarm_subtype', models.CharField(max_length=50)),
                ('alarm_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_counting_data', to='cross_counting.camera')),
            ],
            options={
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['time', 'camera'], name='cross_count_time_2bf228_idx'), models.Index(fields=['device_ip', 'channel'], name='cross_count_device__46b61e_idx'), models.Index(fields=['alarm_subtype', 'alarm_status'], name='cross_count_alarm_s_f8ed9c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['name', 'status'], name='cross_count_name_878f99_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['tag'], name='cross_count_tag_id_55c6bb_idx'),
        ),
    ]
