# Generated by Django 5.2.4 on 2025-07-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_counting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crosscountingdata',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='cross_count_time_2bf228_idx',
        ),
        migrations.RemoveField(
            model_name='crosscountingdata',
            name='time',
        ),
        migrations.AddField(
            model_name='tag',
            name='occupancy',
            field=models.PositiveIntegerField(default=0, help_text='Maximum allowed occupancy for this tag'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['created_at', 'camera'], name='cross_count_created_2aa9f4_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['occupancy'], name='cross_count_occupan_e17b61_idx'),
        ),
    ]
