# Generated by Django 5.2.4 on 2025-07-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_counting', '0002_alter_crosscountingdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_link',
            field=models.CharField(max_length=500),
        ),
    ]
