# Generated by Django 5.2.4 on 2025-07-31 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('occupancy', models.PositiveIntegerField(db_index=True, default=0, help_text='Maximum allowed occupancy for this tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='cross_count_name_aa42b9_idx'), models.Index(fields=['occupancy'], name='cross_count_occupan_6aaff8_idx'), models.Index(fields=['created_at'], name='cross_count_created_702e6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('rtsp_link', models.CharField(max_length=500)),
                ('hls_link', models.CharField(max_length=500)),
                ('status', models.BooleanField(db_index=True, default=True)),
                ('last_data_received', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cross_counting.region')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'status'], name='cross_count_name_878f99_idx'), models.Index(fields=['last_data_received'], name='cross_count_last_da_58be5a_idx'), models.Index(fields=['created_at'], name='cross_count_created_b43980_idx')],
            },
        ),
    ]
