# Generated by Django 5.2.4 on 2025-07-31 19:38

import django.utils.timezone
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_counting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crosscountingdata',
            options={'ordering': ['-created_at', '-time']},
        ),
        migrations.AlterField(
            model_name='crosscountingdata',
            name='time',
            field=timescale.db.models.fields.TimescaleDateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, interval='1 day', null=True),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['created_at', 'camera'], name='ts_created_camera_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['camera', 'created_at', 'cc_total_count'], name='ts_camera_created_total_idx'),
        ),
    ]
