# Generated by Django 5.2.4 on 2025-07-31 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_counting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossCountingData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(db_index=True, max_length=200)),
                ('device_ip', models.GenericIPAddressField(db_index=True)),
                ('device_mac', models.CharField(max_length=17)),
                ('device_phy', models.CharField(blank=True, max_length=50)),
                ('channel', models.CharField(db_index=True, max_length=200)),
                ('channel_alias', models.CharField(blank=True, max_length=200)),
                ('cc_in_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('cc_out_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('cc_total_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('alarm_snapshot', models.BooleanField(default=False)),
                ('alarm_subtype', models.CharField(db_index=True, max_length=50)),
                ('alarm_status', models.BooleanField(db_index=True, default=False)),
                ('record_flag', models.CharField(blank=True, max_length=10)),
                ('subscribe_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data_pos', models.PositiveIntegerField(blank=True, null=True)),
                ('alarm_time', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_counting_data', to='cross_counting.camera')),
            ],
            options={
                'db_table': 'cross_counting_data_timeseries',
                'ordering': ['-alarm_time', '-created_at'],
                'indexes': [models.Index(fields=['camera', 'alarm_time'], name='cross_count_camera__4cdf8f_idx'), models.Index(fields=['channel', 'alarm_time'], name='cross_count_channel_b0ba6d_idx'), models.Index(fields=['cc_total_count', 'alarm_time'], name='cross_count_cc_tota_badba6_idx'), models.Index(fields=['device_name', 'alarm_time'], name='cross_count_device__305088_idx'), models.Index(fields=['created_at'], name='cross_count_created_d08fce_idx')],
            },
        ),
    ]
