# Generated by Django 5.2.4 on 2025-07-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_counting', '0002_crosscountingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPeakView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('peak_in_count', models.PositiveIntegerField()),
                ('peak_out_count', models.PositiveIntegerField()),
                ('peak_total_count', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'cross_counting_daily_peaks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HourlyAggregateView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField()),
                ('max_in_count', models.PositiveIntegerField()),
                ('max_out_count', models.PositiveIntegerField()),
                ('max_total_count', models.PositiveIntegerField()),
                ('min_in_count', models.PositiveIntegerField()),
                ('min_out_count', models.PositiveIntegerField()),
                ('min_total_count', models.PositiveIntegerField()),
                ('avg_total_count', models.FloatField()),
                ('data_points', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'cross_counting_hourly_aggregates',
                'managed': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='cross_count_camera__4cdf8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='cross_count_channel_b0ba6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='cross_count_cc_tota_badba6_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='cross_count_device__305088_idx',
        ),
        migrations.RenameIndex(
            model_name='crosscountingdata',
            new_name='ts_created_idx',
            old_name='cross_count_created_d08fce_idx',
        ),
        migrations.AlterField(
            model_name='crosscountingdata',
            name='cc_in_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crosscountingdata',
            name='cc_out_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crosscountingdata',
            name='cc_total_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['alarm_time', 'camera'], name='ts_time_camera_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['alarm_time', 'channel'], name='ts_time_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['alarm_time', 'device_name'], name='ts_time_device_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['camera', 'alarm_time', 'cc_total_count'], name='ts_camera_time_total_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['channel', 'alarm_time', 'cc_in_count', 'cc_out_count'], name='ts_channel_time_counts_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(condition=models.Q(('alarm_status', True)), fields=['alarm_time', 'camera'], name='ts_active_alarms_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['alarm_time', 'alarm_status'], name='ts_time_status_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['device_name', 'alarm_time', 'alarm_status'], name='ts_device_time_status_idx'),
        ),
    ]
