# Generated by Django 5.2.4 on 2025-07-31 20:24

import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_counting', '0002_alter_crosscountingdata_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_time_camera_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_time_channel_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_time_device_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_camera_time_total_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_channel_time_counts_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_active_alarms_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_device_time_status_idx',
        ),
        migrations.AlterField(
            model_name='crosscountingdata',
            name='time',
            field=timescale.db.models.fields.TimescaleDateTimeField(blank=True, db_index=True, interval='1 day', null=True),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['created_at', 'channel'], name='ts_created_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['created_at', 'device_name'], name='ts_created_device_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['channel', 'created_at', 'cc_in_count', 'cc_out_count'], name='ts_channel_created_counts_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(condition=models.Q(('alarm_status', True)), fields=['created_at', 'camera'], name='ts_active_alarms_created_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['device_name', 'created_at', 'alarm_status'], name='ts_device_created_status_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['camera', 'created_at'], name='ts_camera_created_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['created_at', 'cc_in_count'], name='ts_created_in_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['created_at', 'cc_out_count'], name='ts_created_out_idx'),
        ),
    ]
