# Generated by Django 5.2.4 on 2025-07-31 09:38

import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_counting', '0003_dailypeakview_hourlyaggregateview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crosscountingdata',
            options={'ordering': ['-time', '-alarm_time']},
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_time_channel_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_time_device_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_camera_time_total_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_channel_time_counts_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_active_alarms_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_device_time_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_time_camera_idx',
        ),
        migrations.RemoveIndex(
            model_name='crosscountingdata',
            name='ts_time_status_idx',
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['alarm_time', 'camera'], name='ts_alarm_time_camera_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['alarm_time', 'alarm_status'], name='ts_alarm_time_status_idx'),
        ),
        migrations.AddField(
            model_name='crosscountingdata',
            name='time',
            field=timescale.db.models.fields.TimescaleDateTimeField(blank=True, db_index=True, interval='1 day', null=True),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['time', 'camera'], name='ts_time_camera_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['time', 'channel'], name='ts_time_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['time', 'device_name'], name='ts_time_device_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['camera', 'time', 'cc_total_count'], name='ts_camera_time_total_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['channel', 'time', 'cc_in_count', 'cc_out_count'], name='ts_channel_time_counts_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(condition=models.Q(('alarm_status', True)), fields=['time', 'camera'], name='ts_active_alarms_idx'),
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(fields=['device_name', 'time', 'alarm_status'], name='ts_device_time_status_idx'),
        ),
    ]
