# Generated by Django 5.2.4 on 2025-07-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_counting', '0003_dailypeakview_hourlyaggregateview_and_more'),
        ('cross_counting', '0003_optimize_timeseries_indexes'),
    ]

    operations = [
    ]
