# Generated by Django 5.2.4 on 2025-07-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_counting', '0005_create_materialized_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPeakView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('peak_in_count', models.PositiveIntegerField()),
                ('peak_out_count', models.PositiveIntegerField()),
                ('peak_total_count', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'cross_counting_daily_peaks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HourlyAggregateView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField()),
                ('max_in_count', models.PositiveIntegerField()),
                ('max_out_count', models.PositiveIntegerField()),
                ('max_total_count', models.PositiveIntegerField()),
                ('min_in_count', models.PositiveIntegerField()),
                ('min_out_count', models.PositiveIntegerField()),
                ('min_total_count', models.PositiveIntegerField()),
                ('avg_total_count', models.FloatField()),
                ('data_points', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'cross_counting_hourly_aggregates',
                'managed': False,
            },
        ),
        migrations.AddIndex(
            model_name='crosscountingdata',
            index=models.Index(condition=models.Q(('alarm_status', True)), fields=['alarm_time', 'camera'], name='ts_active_alarms_idx'),
        ),
    ]
